### Data Structures

#### List-> Elements are separated by comma and enclosed with square bracket

#### hetrogeneous

#### List can be retrieved using index

#### Mutable

In [4]:
sample_list=[1,13.6,"hi",12,1]
sample_list

[1, 13.6, 'hi', 12, 1]

In [5]:
sample_list[0]

1

In [6]:
sample_list[10]

IndexError: list index out of range

In [7]:
sample_list[-2]

12

In [9]:
sample_list[3]

12

In [10]:
sample_list[0]=100

In [11]:
sample_list

[100, 13.6, 'hi', 12, 1]

### Tuple

#### Heterogeneous
#### Paranthesis
#### Can retrieve data using index
#### Immutable

In [12]:
sample_tuple=(1,13.6,"hi",12,1)
sample_tuple

(1, 13.6, 'hi', 12, 1)

In [13]:
sample_tuple[3]

12

In [14]:
sample_tuple[0]

1

In [15]:
sample_tuple[0]=100

TypeError: 'tuple' object does not support item assignment

### Set

#### Doesnot allow duplicates
#### Ordered-First place
#### In set, elements cannot be retrieved using index
#### set is mutable

In [16]:
sample_set={1,13.6,"hi",12,1,127,25,25,"apple","king","ball"}
sample_set

{1, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [18]:
sample_set[-5]

TypeError: 'set' object is not subscriptable

In [19]:
sample_set[0]="hello"

TypeError: 'set' object does not support item assignment

In [20]:
sample_set.add(1000)

In [21]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [22]:
sample_set.remove("hi")

In [23]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'king'}

### Dictionary
#### Has key-value pair data structure
#### Key is unique
#### Values can be duplicated
#### Value can be retrieved using key
#### key cannot be retrieved using index

In [26]:
sample_dict={1:"apple",2:35.4,3:"data",2:"every",6:"35.4",7:35.4}
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 35.4}

In [27]:
sample_dict[1]

'apple'

In [28]:
sample_dict["apple"]

KeyError: 'apple'

In [32]:
sample_dict[7]=100
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 100}

In [33]:
sample_dict[10]="Business"
sample_dict

{1: 'apple', 2: 'every', 3: 'data', 6: '35.4', 7: 100, 10: 'Business'}

In [ ]:
#### how to add key value pair to a dictionary?

### Numpy: package for multidimensional array

In [35]:
import numpy as np

In [36]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [40]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### shift+tab= help box

In [41]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [44]:

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.ones(25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
np.ones(50,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [48]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##### Create an array of zeros with 2 rows and 10 columns

In [49]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

###### I LOVE U MUTHUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

In [50]:
import numpy as np

In [51]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [52]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [53]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
np.random.rand(3,2)

array([[0.81145228, 0.67586801],
       [0.50063405, 0.34089143],
       [0.31347324, 0.94301007]])

In [55]:
np.random.randn(3,2)

array([[ 1.16875572, -0.66672351],
       [-0.35180111,  0.99831683],
       [ 0.87369342, -0.00741415]])

In [56]:
np.random.randint(34,100)

94